export const VALID_CITIES = [
  'Windsor',
  'Barrie',
  'Port Hope',
  'London',
  'Toronto',
  'Hamilton',
  'Whitby',
  'Thorold',
  'Newmarket',
  'Cornwall',
  'Oakville',
  'Kingston',
  'Point Edward',
  'Ottawa',
  'Mississauga',
  'Waterloo',
  'Guelph',
  'Stratford',
  'St. Thomas',
  'Chatham',
  'Simcoe',
  'Brantford',
  'Thunder Bay',
  'New Liskeard',
  'Brockville',
  'Peterborough',
  'Timmins',
  'North Bay',
  'Sudbury',
  'Belleville',
  'Pembroke',
  'Sault Ste. Marie',
  'Owen Sound',
  'Kenora'
];
